services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapper
    restart: on-failure:5 
    networks:
      - nginx-network
    ports:
      - "${PORT:-8000}:8000"  # Use environment variable for port
    environment:
      - PORT=8000  # Render sets this automatically
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port ${PORT:-8000} --workers 2 --http auto --access-log
